### PR TITLE
Ongoing Development

### PR DESCRIPTION
**Pull request by martin-ueding**
A pull request for ongoing development, though no focused goal.

### CODE REVIEW

**Comment by martin-ueding** [comment]
Besides potential bugs anywhere I can now create the prescription for all the GEVPs. The following association has the following levels:

1. Total momentum
2. Irrep
3. GEVP row label (relative momentum for now)
4. GEVP column label
5. HDF5 data set name, a `conj:` prefix means that the computed one has to be complex conjugated
6. Real or complex weight factor

The following is for the rho channel but only with a single total momentum, single irrep and few relative momenta. The full calculation is possible, but will just take hours. For testing this is much easier.

I'll start writing the actual HDF5 file number crunching next.

---

```js
{
  "001": {
    "A1": {
      "000": {
        "000": {
          "C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 32, 
          "C4cD_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 32, 
          "C4cD_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -32, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16
        }, 
        "001": {
          "C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -32, 
          "C4cD_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -32, 
          "C4cD_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -32, 
          "C4cD_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 32, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16
        }
      }, 
      "001": {
        "000": {
          "C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "C4cD_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": -32, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": -16
        }, 
        "001": {
          "C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": 16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "C4cD_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": -32, 
          "C4cD_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": 32, 
          "C4cD_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": 32, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": 16, 
          "C4cV_uuuu_g5.p000.d000_g5.p001.d000_g5.p001.d000_g5.p000.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": 16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p000.d000_g5.p001.d000": -16, 
          "C4cV_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p00-1.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p00-1.d000_g5.p000.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p00-1.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p00-1.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p000.d000_g5.p001.d000_g5.p001.d000": 16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p00-1.d000": -16, 
          "conj:C4cB_uuuu_g5.p000.d000_g5.p001.d000_g5.p000.d000_g5.p001.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p00-1.d000_g5.p000.d000_g5.p000.d000": 16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p00-1.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p000.d000_g5.p001.d000_g5.p000.d000": -16, 
          "conj:C4cB_uuuu_g5.p001.d000_g5.p001.d000_g5.p000.d000_g5.p000.d000": 16
        }
      }
    }
  }
}
```

**Comment by kostrzewa** [comment]
At what stage do you apply the twisted-mass specific flavour change under g5 hermiticity? Of course, this generalises in some sense to Wilson fermions as there the flavours are simply the same, but perhaps it is necessary to be mindful of this.

What about support for flavours other than "light" quarks? It's not important to have this right now, but it would be a shame if you do so much work now and get stuck in a corner where generalisations become very difficult or impossible without major work.

**Comment by martin-ueding** [comment]
The quark operators are written with certain flavors, which are just strings. I have `"up"` and `"dn"`, but that can be whimsically chosen.

Auswahl_035

The Wick contractions give me propagators, these are ignorant to the exact flavors as well.

Auswahl_036

The flavor change under γ₅ comes in because I replace these trace expressions with charged/conjugated diagrams that have this included. The replacement rules (with `:>`, infix for `RuleDelayed`) look like the following:

```mathematica
  (* C4cB *)
  qct`trace[qct`Gamma^g1_ . prop["up", so[so1_]].
    qct`Gamma^g2_ . prop["dn", si[si2_]].
    qct`Gamma^g3_ . prop["up", si[si3_]].
    qct`Gamma^g4_ . prop["dn", so[so4_]]] :> 
  TemplateApply[
    "C4cB_uuuu_" <> MakeTemplate[4],
    <|"g1" -> g1, "g2" -> g2, "g3" -> g3, "g4" -> g4,
      "x1" -> "`pso" <> ToString @ so1 <> "`",
      "x2" -> "`psi" <> ToString @ si2 <> "`",
      "x3" -> "`psi" <> ToString @ si3 <> "`",
      "x4" -> "`pso" <> ToString @ so4 <> "`"|>],
```

A trace expression is mapped to a `C4cB_uuuu` diagram only if it has the exact flavors in the propagators. One could add say a `C4cB_suuu` diagram with Kπ scattering if one matches to flavors `{"s", "dn", "up", "dn"}`. One can likely be a bit more clever about this and define a mapping from the flavors in the propagators to the ones in the HDF5 dataset name, but I do not see a major hurdle for also supporting more flavors.

**Comment by martin-ueding** [comment]
I did a comparison to Markus' data with d² = 1, A1 and q = 000 this morning. After just one trivial fix the data matches (up to a factor of 128, which we understand). This means that at least this particular moving frame and irrep work out. For the d² = 0 we have identified a problem with the parity and devised a solution for that.

The next steps are the implementation of that parity fix and then a complete generation of the prescription for all moving frames, irreps and relative momenta. Then I will compare with Markus' data and hopefully we find exact agreement.

**Comment by martin-ueding** [comment]
I believe that the bulk of the code is now there and we can have pull requests on topics now.

**Pull request closed without merging**
